# This is a basic workflow to help you get started with Actions

name: Dockerize your Development Server

# Controls when the workflow will run
on:
  push:
    branches: [ "dev" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DEV_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DEV_DOCKER_HUB_ACCESS_TOKEN }}
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
        
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DEV_DOCKER_HUB_USERNAME }}/p3_server:${{ env.GITHUB_RUN_NUMBER }} , ${{ secrets.DEV_DOCKER_HUB_USERNAME }}/p3_server:latest
          
   
          
          
        
      
